from langchain_core.prompts import ChatPromptTemplate

# ─────────────────────────────────────────
# Default Auto Query
# ─────────────────────────────────────────
DEFAULT_QUERY = "Give a summary of the issues mentioned in this file and also provide solutions for each issue."

# ─────────────────────────────────────────
# RAG Prompt Template
# ─────────────────────────────────────────
rag_prompt = ChatPromptTemplate.from_template("""
Answer the question based only on the context below.
With proper formatting and bullet points if needed.
Give proper space between each solution.

In proper email format with subject and greeting and closing.

Give the most updated solution for each issue mentioned in the context and also provide a summary of the issues mentioned in the context.

At the bottom, write that this AI-generated mail is for reference purpose only and also mention that this mail is generated by Sapphire Infotech and also provide the website link of sapphireinfotech (www.sapphireinfotech.co.in) and mention the time and date of mail generation.

Context: {context}

Question: {question}
""")
